const DELETE_ITEM = "DELETE ITEM";
const AUMENTA_QTY = "ADD QTY";
const DIMINUISCI_QTY = "DIM QTY";
const SVUOTA_CARRELLO = "REMOVE ALL";
const COSTO_TOTALE = "SOMMA";
const CONTATORE = "CONTATORE";
const SHOW_CART = "SHOW_CART";
const ADD_CART = "ADD_CART";

export {
  SHOW_CART,
  ADD_CART,
  DELETE_ITEM,
  AUMENTA_QTY,
  DIMINUISCI_QTY,
  SVUOTA_CARRELLO,
  CONTATORE,
  COSTO_TOTALE,
};
